backend:
    name: git-gateway
    branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "artikel"
    label: "Artikel"
    folder: "data/artikel"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Judul", name: "title", widget: "string" }
      - { label: "Kategori", name: "kategori", widget: "string" }
      - { label: "Isi Artikel", name: "body", widget: "markdown" }
      - { label: "Tautan", name: "link", widget: "string" }